### ISSUE TITLE
Out-of-date versions of @okta/okta-react and @okta/okta-signin-widget

### ISSUE THREAD

**Issue by alexvictoor** [okta/samples-js-react#108]
Hello
I am quite new to okta. I have tried to plug okta to an existing react app. I had an hard time figuring out why things where not working in my app while my code was quite similar to the custom login sample...
Using the versions of okta-react and okta-signin-widget used in the samples solved all my problems. 
Latest versions of these two libs may have breaking changes. 
Sadly I have not seen any migration tips from okta-react 2 to okta-react 3 in the doc :(

**Comment by swiftone** [comment]
Hi @alexvictoor, welcome to Okta!  We just updated okta-react to 2.x recently (and to 3.x shortly afterward because our okta-auth-js had a major version update), and we're still going through all of our documentation to make sure it reflects the changes.

Generally speaking we try to include migration information in the README (such as  https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#migrating-from-1x-to-20 ) and any changes should be recorded in the CHANGELOG (such as https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/CHANGELOG.md#300 ).

I also have an update in the works to update this react sample to use the latest versions ( https://github.com/okta/samples-js-react/pull/107 ) 

Do these resolve the difficulties you encountered, or is there something more specific that would help?

**Comment by alexvictoor** [comment]
Thanks a lot for your quick and helpful response!
